### PR TITLE
Fixed News Title Localisation

### PR DESCRIPTION
**Pull request by DavidKrassnig**
Added  modified variant of the _page_ layout named _news_ and converted all news to the _news_ layout. Functionally equivalent to currently displayed news with the exception of working title localization.

### CODE REVIEW

**Comment by DavidKrassnig** [comment]
I originally tried to fix this by fixing the _post_ layout, but for some reason that kept crashing (using the very same code with regards to the title as in the new _news_ layout).

**Comment by george-gca** [comment]
I believe this is the cleanest possible solution. I also previously struggled with this, and added a `TODO` somewhere for me to remember to take a look at it.

What happens with the post layout is that the title and the contents are not translated via `t` tag. Instead, all of its contents are fetched from the localized `_posts` directories. When you try to translate the title in the `post` layout, it did ok for the `news`, but it also tries to translate the title of the posts that are already translated, so it ends looking for a key in the translation files that is the actual title. Something like looking for the key `a post with formatting and links` in the translation files.

Thanks for the contribution btw.

**Comment by DavidKrassnig** [comment]
By the way, not certain what exactly changed because I've been away for quite some while, but the error is back. You seem to have gone from *.html files to *.liquid files but there no longer appears to be a news.html (or rather news.liquid under the current system).
Should I open a new issue on this?

**Comment by george-gca** [comment]
Hummmm I probably missed this while merging new changes from al-folio into this repository. Will try to fix this.

**Comment by george-gca** [comment]
Fixed @DavidKrassnig

**Pull request merged**
